### ISSUE TITLE
Brian deleted my space content!

### ISSUE THREAD

**Issue by naelstrof** [naelstrof/SpaceJanitor#1]
The entire Effects folder within restricted assets was deleted, among other things.

Did you mean to do that Brian? If not how should I refactor the pile of commits that you've made? One of them is too large to view, and it seems as though you've "undone" my entire space asset commit.

**Comment by zfrye06** [comment]
I don't think he did. I just realized that I got a call from him yesterday saying that he was trying to revert his commit to un-delete your changes and couldn't figure it out.

**Comment by zfrye06** [comment]
I just undid all of Brian's commits just now, hopefully nothing was lost.
